services:
  translaitor:
    container_name: translaitor
    image: node:lts-alpine
    ports:
      - "8001:3000"
    volumes:
      - ./app:/workspace
    networks:
      - traefik_default
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      # For production deployment
      - BODY_SIZE_LIMIT=50M
    working_dir: /workspace
    command: sh /workspace/script.sh
    restart: unless-stopped

networks:
  traefik_default:
    name: traefik_default
    external: true
