services:
  translaitor:
    container_name: translaitor
    image: node:lts-alpine
    ports:
      - "8001:3000"
    volumes:
      - ./app:/workspace
    networks:
      - traefik_default
    env_file:
      - .env
    working_dir: /workspace
    command: sh /workspace/script.sh
    restart: unless-stopped

networks:
  traefik_default:
    name: traefik_default
    external: true
